nelmio_cors:
    defaults:
        allow_credentials: true
        allow_origin: ['*']  # Change '*' to your specific domain for production
        allow_headers: ['*']
        allow_methods: ['GET', 'POST', 'PUT', 'DELETE', 'OPTIONS']
        expose_headers: []
        max_age: 3600
