<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerA26JO1N\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerA26JO1N/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerA26JO1N.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerA26JO1N\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerA26JO1N\App_KernelDevDebugContainer([
    'container.build_hash' => 'A26JO1N',
    'container.build_id' => '31c714ad',
    'container.build_time' => 1721906372,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerA26JO1N');
