<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container2UbAGwR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container2UbAGwR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container2UbAGwR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container2UbAGwR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container2UbAGwR\App_KernelDevDebugContainer([
    'container.build_hash' => '2UbAGwR',
    'container.build_id' => '9fb09bfb',
    'container.build_time' => 1721899560,
], __DIR__.\DIRECTORY_SEPARATOR.'Container2UbAGwR');
